# Generated by Django 5.1.2 on 2024-10-20 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_booking_mechanic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='car_registration_plate',
            field=models.CharField(max_length=50),
        ),
    ]
