name: car_workshop_app
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  get: ^4.6.6
  get_storage: ^2.1.1
  http: ^1.2.1
  smooth_page_indicator: ^1.1.0
  lottie: ^3.1.2
  awesome_snackbar_content: ^0.1.3
  flutter_staggered_animations: ^1.0.0
  table_calendar: ^3.0.0
  intl: ^0.18.1
  google_fonts: ^6.1.0
  url_launcher: ^6.2.1



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1  # Ensure the version number is aligned correctly

flutter_icons:  # Corrected key name
  android: true
  ios: true
  image_path: "assets/default.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/default.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/default.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/default.png"



flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/on_boarding/
